### ISSUE TITLE
"Find Me on Meower!" Badge

### ISSUE THREAD

**Issue by Mwalters75** [meower-media-co/Meower-Vanilla#100]
Hi, I had recently joined the Meower Media Co. team, and I had made a badge that can be used for attracting more users to Meower:
![Find me On (Project) Meower!](https://user-images.githubusercontent.com/67456566/146070466-1ac678e5-ebee-4fb9-8c3b-92d59503bc31.png)
If it can be accepted for usage, that would be great!

**Comment by MikeDev101** [comment]
Find a slightly higher quality image of the logo and it's ok.

(also, please use #3 next time for discussions not related to issues with Meower.)

**Comment by CST1229** [comment]
#100 🎉
