### ISSUE TITLE
Design a better chat

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Vanilla#101]
<div type='discussions-op-text'>

<sup>Originally posted by **MikeDev101** December 14, 2021</sup>
From the old 4.6 update announcement:

The current Meower chat system is barebones, and can use some improvement. Here's a suggestion from a while ago:

![image](https://user-images.githubusercontent.com/12957745/146041996-2bcc980c-1c6a-4b0a-b800-ee6d31ca352b.png)

(Ignore mentions of BlueList, we do not speak of it)</div>

**Comment by yoo832** [comment]
you forgot ~strikethrough~

**Comment by meguy7878** [comment]
> you forgot ~strikethrough~

For what?

**Comment by Josiah76** [comment]
I will try to make the chat better and merry Christmas!

**Comment by MikeDev101** [comment]
I did not ask for assignees. I asked for more ideas.

**Comment by MikeDev101** [comment]
Actually, since Beta 5 will be removing support for BBCode, this is more or less not needed. Closing.
