### ISSUE TITLE
Meower Beta Test (4.7) doesn't load in E羊icques.

### ISSUE THREAD

**Issue by GhostedNotFound** [meower-media-co/Meower-Vanilla#103]
When trying to load the latest Meower.sb3 file via E羊icques, after a while of loading, it says:

![image](https://user-images.githubusercontent.com/84326942/146102438-30e5369f-9407-4bba-889c-1300d0f70498.png)

I am using an HP Chromebook so I don't know if it has something to do with my crappy Chromebook or E羊icques can't load it for some reason.

**Comment by MikeDev101** [comment]
That's because it uses a custom TurboWarp block for getting keyboard input. I'm going to be removing it in the next beta.

**Comment by wgyt** [comment]
even if we were to remove this block, cloudlink trusted access isn't in the SB3, but I have a way to fix this without leaking the key

**Comment by CST1229** [comment]
> even if we were to remove this block, cloudlink trusted access isn't in the SB3, but I have a way to fix this without leaking the key

Probably checking for the origin of the request?

**Comment by wgyt** [comment]
> Probably checking for the origin of the request?
That isn't what I was going to do, I was going to add an extension that does stuff for new build pipeline
