### ISSUE TITLE
[BUG] uBlock, Brave Shield, etc. cause meower to block you

### ISSUE THREAD

**Issue by VelocityDesign** [meower-media-co/Meower-Vanilla#108]
Note: This only happens while adblocking is active.

**Comment by CST1229** [comment]
This is due to the IP address detector Meower uses

**Comment by Melt2002** [comment]
This can't be fixed, due to these platforms blocking the IP from being grabbed.

**Comment by Voxalice** [comment]
Turn off your adblocker for Meower, or write an exception filter for api.ipify.org.

**Comment by MikeDev101** [comment]
marking as published for my todo list. Meower API isn't blocked by adblockers or firewalls by default, and Beta 5 fixes this bug.
