### ISSUE TITLE
Switch to one main logo instead of several variations

### ISSUE THREAD

**Issue by Melt2002** [meower-media-co/Meower-Vanilla#111]
There are several variations of the Meower logo. There's the one you see most, which is just "meower" typed out in the font, then there is "MEOWER" designed to look like the Scratch logo (which needs changed or removed), and then there's this logo.
![image](https://user-images.githubusercontent.com/62972395/146649759-cf0ec644-3a2b-4001-b3b8-02526ecdf675.png)
(this one is for meower media co though, so it's probably fine?)

We need one main logo.

**Comment by CST1229** [comment]
Also there's Meowy for the icon for meower media co.

**Comment by Melt2002** [comment]
This has been fixed with the Meower logo rebrand.
