### ISSUE TITLE
Meower can't connect on TurboWarp

### ISSUE THREAD

**Issue by Mwalters75** [meower-media-co/Meower-Vanilla#115]
Every time I try to load Meower on TurboWarp doesn't work. Here's a screenshot of the error:

![Error on TurboWarp](https://user-images.githubusercontent.com/67456566/146696627-40b70934-638a-4840-b52a-62fca8dec0d2.png)

**Comment by Samq64** [comment]
You need to setup a local Meower server: https://github.com/meower-media-co/Meower-server#readme

**Comment by Mwalters75** [comment]
Do I have to?

**Comment by MikeDev101** [comment]
For security purposes, the publically available source code of Meower doesn't have a valid security key to gain trust on the Meower server. To demo the source code, you will need to be running a local meower server.

**Comment by CST1229** [comment]
Speaking of trusted access, you can already find the security key with a bit of searching in the project.json of the meower.org release of meower, which you can find pretty easily too.

**Comment by MikeDev101** [comment]
> Speaking of trusted access, you can already find the security key with a bit of searching in the project.json of the meower.org release of meower, which you can find pretty easily too.

That is true, we plan on obfuscating this through custom JS provided through Github secrets, but this is still in the planning stages.

**Comment by CST1229** [comment]
> That is true, we plan on obfuscating this through custom JS provided through Github secrets, but this is still in the planning stages.

What about some other way of implementing trusted access, like with CORS?  Ofc people would still be able to bypass it but it will be a slight bit harder and plus you can combine it with other types of security.

**Comment by Mwalters75** [comment]
I think I just won't use Meower on TurboWarp. Thanks anyway!

**Comment by MikeDev101** [comment]
> > That is true, we plan on obfuscating this through custom JS provided through Github secrets, but this is still in the planning stages.
> 
> What about some other way of implementing trusted access, like with CORS? Ofc people would still be able to bypass it but it will be a slight bit harder and plus you can combine it with other types of security. (BTW, also how would custom JS be providable by github secrets?)

something @wgyt mentioned in dizzycord. Idk how they planned it would work. more r&d needed.

**Comment by wgyt** [comment]
> > What about some other way of implementing trusted access, like with CORS? Ofc people would still be able to bypass it but it will be a slight bit harder and plus you can combine it with other types of security. (BTW, also how would custom JS be providable by github secrets?)
> 
> something @wgyt mentioned in dizzycord. Idk how they planned it would work. more r&d needed.
that was an idea for new pipeline, but i realized its a PITA to do new pipeline with built in packager, so we would need to build the html file ourselves and pushing it, making the custom JS idea pointless when we can just add the key manually

**Comment by tnix100** [comment]
Also there's still the way of just opening your developer console, going to network and watching the WebSocket connection.

**Comment by Bloctans** [comment]
meower is now a key of the meower server, can be fixed by changing the server to connect to to server.meower.org.

**Comment by Mwalters75** [comment]
It says that it has a bad gateway error

**Comment by Mwalters75** [comment]
> Did you setup a local Meower server? https://github.com/meower-media-co/Meower-server#readme

Half a month later, I figured it out.
