### ISSUE TITLE
Use API for IP address instead

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Vanilla#125]
^

API can be accessed via https://api.meower.org
Currently under construction but works

IP fetcher is at https://api.meower.org/ip

**Comment by Mwalters75** [comment]
Is the source code publicly avalible?

**Comment by CST1229** [comment]
> Is the source code publicly avalible?

Yes, here.

**Comment by MikeDev101** [comment]
Marking as "ready for testing" in my todo list

**Comment by Mwalters75** [comment]
> > Is the source code publicly avalible?
> 
> Yes, here.

I don't see it, though.

**Comment by CST1229** [comment]
> > > Is the source code publicly avalible?
> > 
> > 
> > Yes, here.
> 
> I don't see it, though.

![](https://user-images.githubusercontent.com/68464103/148989066-468d8d76-503a-4c01-b33c-f72741fc4e04.png)

The server code is [here](https://github.com/meower-media-co/Meower-Server) (previously it was on this repo).

**Comment by Mwalters75** [comment]
@MikeDev101
![Screenshot 2022-01-11 6 14 36 PM](https://user-images.githubusercontent.com/67456566/149036260-78b5188f-c4e3-446e-95f2-34747a3d2652.png)

**Comment by MikeDev101** [comment]
Needed to bring down server for fixing
should be back up now

temporarily reusing the old IP fetcher

**Comment by MikeDev101** [comment]
closing as implemented
