### ISSUE TITLE
Switch to Stamp Font Engine++

### ISSUE THREAD

**Issue by CloudGate1234** [meower-media-co/Meower-Vanilla#128]
Stamp Font Engine++ is @-rex-'s newest font engine and it is far better than the current Pen Text Engine++ (also made by -rex-) 
link: https://scratch.mit.edu/projects/589579521/
![image](https://user-images.githubusercontent.com/88938765/148845316-369c2718-f589-4dfe-aa52-f556f00e3cc5.png)
![image](https://user-images.githubusercontent.com/88938765/148845456-afef5388-4661-444e-8401-b276ba7eda7d.png)

**Comment by MikeDev101** [comment]
As of now Meower Beta 5 Preview 1.1 uses the old Stamp Font Engine. I suppose it wouldn't be too hard to upgrade the engine.

**Comment by MikeDev101** [comment]
...and meower is breaking. great. 
![image](https://user-images.githubusercontent.com/12957745/148859602-d7f5a4b5-1fcc-44a2-831e-8e9c45594afc.png)
![image](https://user-images.githubusercontent.com/12957745/148859911-b2eb2085-1cf8-449f-8ef6-a5d4087f5538.png)

**Comment by MikeDev101** [comment]
deprioritizing because of annoying

**Comment by MikeDev101** [comment]
![image](https://user-images.githubusercontent.com/12957745/148868466-6d3150c6-2598-4d5b-a4a4-94b5744ca67a.png)

I did it
I saved da worl

**Comment by MikeDev101** [comment]
https://github.com/meower-media-co/Meower-Vanilla/blob/main/Meower%20Beta%205%20Preview%201.2.sb3
