### ISSUE TITLE
Half of the text is in italics

### ISSUE THREAD

**Issue by Mwalters75** [meower-media-co/Meower-Vanilla#131]
Main Menu, Settings, Global Chat(room) is affected by this bug
![Screenshot 2022-01-12 10 49 40 AM](https://user-images.githubusercontent.com/67456566/149174860-98139fc0-f0f5-4453-b80e-82ed37e8eacf.png)
![Screenshot 2022-01-12 10 59 43 AM](https://user-images.githubusercontent.com/67456566/149175784-4b0fdf8e-2525-4582-9299-e43232b38552.png)
![Screenshot 2022-01-12 10 59 21 AM](https://user-images.githubusercontent.com/67456566/149175787-909afa9c-dde6-4404-99f0-9247aea93df7.png)

**Comment by Mwalters75** [comment]
Closing, because the problem had been fixed.

**Comment by Mwalters75** [comment]
*Problem had been idetified as BBCode+ making the bug*

**Comment by MikeDev101** [comment]
ignoring this bug as bbcode+ is being removed in beta 5

**Comment by Mwalters75** [comment]
https://wiki.meower.org/wiki/Italic_Bug

**Comment by Bloctans** [comment]
can be fixed by posting [/b]

**Comment by Mwalters75** [comment]
Bug's back.

**Comment by Samq64** [comment]
Um... I noticed this happened after posting the post after the one with BBCode in it.
![image](https://user-images.githubusercontent.com/81489795/149558880-1e105169-d224-4197-9657-3a9a31503caa.png)

Edit: Is that what you meant by the container bug?

**Comment by MikeDev101** [comment]
....how.

yeah bbcode+ is really broken lmao

**Comment by Mwalters75** [comment]
> I noticed this happened after posting a post after one with BBCode in it. Is it related to BBCode+? ![image](https://user-images.githubusercontent.com/81489795/149558880-1e105169-d224-4197-9657-3a9a31503caa.png)
> 
> Edit: Is that what you meant by the container bug?

3 posts down, yes.

**Comment by Mwalters75** [comment]
Closing, becasue the bug's gone... Will re-open if bug comes back.

**Comment by Mwalters75** [comment]
It's that time again.

**Comment by MikeDev101** [comment]
> > ignoring this bug as bbcode+ is being removed in beta 5

It's that time again.

**Comment by Mwalters75** [comment]
> > > ignoring this bug as bbcode+ is being removed in beta 5
> 
> It's that time again.

At least we have Beta 5.
