### ISSUE TITLE
Meower doesn't post if post contents contain `"`

### ISSUE THREAD

**Issue by Mwalters75** [meower-media-co/Meower-Vanilla#140]
This is very bad, if you're trying to quote somebody.
![image](https://user-images.githubusercontent.com/67456566/149704372-bfe15f3d-15ba-4e34-80a4-2c18056cbec4.png)
![Screenshot 2022-01-18 4 19 02 PM](https://user-images.githubusercontent.com/67456566/150020418-ce6822d5-04ba-489e-8468-a9141826dc4c.png)

**Comment by MikeDev101** [comment]
datatype-related errors. It's a pain. Working on it-

**Comment by Bloctans** [comment]
> This is very bad, if you're trying to quote somebody. ![image](https://user-images.githubusercontent.com/67456566/149704372-bfe15f3d-15ba-4e34-80a4-2c18056cbec4.png) ![Screenshot 2022-01-18 4 19 02 PM](https://user-images.githubusercontent.com/67456566/150020418-ce6822d5-04ba-489e-8468-a9141826dc4c.png)

ah yes, programming related. mikedevs working on it tho, so ill close this.
