### ISSUE TITLE
How to post on Beta 5 1.3?

### ISSUE THREAD

**Issue by Mwalters75** [meower-media-co/Meower-Vanilla#141]
I noticed, right after making a Meower Server (on repl.it, thanks to the people who left a comment in #115), I noticed that there's visually no way to post on Beta 5.
![Screenshot 2022-01-18 2 07 29 PM](https://user-images.githubusercontent.com/67456566/150003230-e65b7090-f83a-48c0-bce7-6c1f15530029.png)
<sup>Yes, I packaged it.</sup>

**Comment by MikeDev101** [comment]
As of now the only way to create a post is to press the spacebar and start
typing. Press enter to send. The next preview will add a graphical post
create button.

**Comment by Mwalters75** [comment]
Thanks!

**Comment by Mwalters75** [comment]
Pretty much the fastest time anybody answered my issue 👍
