### ISSUE TITLE
Improve networking performance by upgrading to CloudLink TURBO

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Vanilla#142]
^

Current CL implementation when downloading posts: From 10-30 Seconds
CL Turbo custom implementation: 0.9-3 Seconds.

Turbo is nice and fast, but it requires custom code to make it work. I will be working on upgrading Beta 5 to use CL turbo.

**Comment by CST1229** [comment]
What is CL Turbo?

**Comment by MikeDev101** [comment]
> What is CL Turbo?

https://github.com/MikeDev101/mikedev101.github.io/blob/master/turbo_networking.js

It's a very fast websocket extension, designed to work in an un-sandboxed scratch mod. It implements a packet queuing system to get lots of spammed packets and hat blocks to function as events. This also gives Meower very low-level access to the CloudLink protocol used to communicate with Meower's servers. Because of it's un-sandboxed nature, it runs extremely fast.

**Comment by Mwalters75** [comment]
> > What is CL Turbo?
> 
> https://github.com/MikeDev101/mikedev101.github.io/blob/master/turbo_networking.js
> 
> It's a very fast websocket extension, designed to work in an un-sandboxed scratch mod. It implements a packet queuing system to get lots of spammed packets and hat blocks to function as events. This also gives Meower very low-level access to the CloudLink protocol used to communicate with Meower's servers. Because of it's un-sandboxed nature, it runs extremely fast.

Fast, and introduces new blocks!
![Screenshot 2022-01-22 4 17 22 PM](https://user-images.githubusercontent.com/67456566/150655744-4d2337ff-dcb7-4840-9af3-28594f959dcc.png)
