### ISSUE TITLE
My IP is blocked?

### ISSUE THREAD

**Issue by TermOfficial** [meower-media-co/Meower-Vanilla#145]
USING BETA 5 AND STILL GETTING ERROR:

**Comment by MikeDev101** [comment]
This is a known bug in Beta 4.x. Please ignore until Beta 5 is released, as this build attempts to fix this bug.

**Comment by MikeDev101** [comment]
Duplicate of https://github.com/meower-media-co/Meower-Vanilla/issues/102

**Comment by TermOfficial** [comment]
oh, i was using beta 5.x

**Comment by MikeDev101** [comment]
then see #102 for more info

**Comment by TermOfficial** [comment]
Nope, no failed to fetch IP.

**Comment by TermOfficial** [comment]
nevermind, just tried using adacraft, and it worked for some reason.
