### ISSUE TITLE
Custom Profile Picture Addition

### ISSUE THREAD

**Issue by Mwalters75** [meower-media-co/Meower-Vanilla#146]
I had recently made a custom profile picture... It's a SVG, so it will be high-quality:

![Yummy!](https://user-images.githubusercontent.com/67456566/151812941-11329146-cff9-49a2-818d-3bc3683dd9b9.svg)

**Comment by Melt2002** [comment]
Isn't that a Mozilla emoji?

**Comment by Melt2002** [comment]
It is a Mozilla emoji. The 😋 emoji to be exact.
https://emojipedia.org/face-savoring-food/

**Comment by Mwalters75** [comment]
> Isn't that a Mozilla emoji?

It's now called fxemoji, due to it's deprecation. It's also open-source: https://github.com/mozilla/fxemoji/

**Comment by Mwalters75** [comment]
Did it get added?

**Comment by Melt2002** [comment]
> Did it get added?

No, the name made it seem like it was asking to add custom profile pictures (like images), which has already been denied. Try opening another issue asking to add a new PFP, and make sure to clarify it's a new PFP you want added and NOT custom image profile pictures.
