### ISSUE TITLE
Post Creation in Private Rooms

### ISSUE THREAD

**Issue by HAZARD6896** [meower-media-co/Meower-Vanilla#151]
Not sure if this is correct place to do this, but posts can't be made in private rooms for me. @Voxalice can, but I cannot

**Comment by Melt2002** [comment]
Cannot replicate this issue.

**Comment by underfanreal** [comment]
press space.

**Comment by MikeDev101** [comment]
Closed. Press space to start typing or press the "+" on the top/sidebar.
