### ISSUE TITLE
Request: Copy+Paste support

### ISSUE THREAD

**Issue by underfanreal** [meower-media-co/Meower-Vanilla#158]
Ctrl+ C and Ctrl+ V would be nice

**Comment by Melt2002** [comment]
Is this even possible with Scratch? I don't think so.

**Comment by CST1229** [comment]
> Is this even possible with Scratch? I don't think so.

TurboWarp can detect Ctrl so it's possible to add a project clipboard. If the clipboard cloud variable behavior is implemented in the packager I think we can use that for interacting with the browser clipboard too.

**Comment by Melt2002** [comment]
> > Is this even possible with Scratch? I don't think so.
> 
> TurboWarp can detect Ctrl so it's possible to add a project clipboard. If the clipboard cloud variable behavior is implemented in the packager I think we can use that for interacting with the browser clipboard too.

Don't think it is, plus it wouldn't be possible to test without packaging which would be a burden.

**Comment by CST1229** [comment]
> Don't think it is, plus it wouldn't be possible to test without packaging which would be a burden.

We can use eval to set or get the clipboard I think.

**Comment by wgyt** [comment]
> > Don't think it is, plus it wouldn't be possible to test without packaging which would be a burden.
> 
> We can use eval to set or get the clipboard I think.

yeah

**Comment by underfanreal** [comment]
I'm gonna close this. As the OP, I have found a way.

By using the Meower Bridge, I can copy paste in there then send something.
