### ISSUE TITLE
Cursor when typing

### ISSUE THREAD

**Issue by ghost** [meower-media-co/Meower-Vanilla#162]
There should be a cursor indicating where you are typing, this is just a suggestion though.

**Comment by MikeDev101** [comment]
bbcode is not related to this.

A text cursor feature would be nice. But it's not a high enough priority at this time.

**Comment by tnix100** [comment]
Maybe beta 6 thing?

**Comment by MikeDev101** [comment]
Closing as not planned, we are retiring the Vanilla client after the CL4 port.
