### ISSUE TITLE
Animated no internet screen?

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower-Vanilla#164]
as seen in https://scratch.mit.edu/projects/536548772/

**Comment by Samq64** [comment]
Cool idea, but probably not very useful for something that requires internet to load at all. The only time this screen would appear is while fetching posts after losing connection when Meower is already open or attempting to load it as an offline page. In those cases I think a generic error is fine. This would be a good addition to Meower mobile though if it doesn't already exist though.
