### ISSUE TITLE
Bug with posts.

### ISSUE THREAD

**Issue by oofy123** [meower-media-co/Meower-Vanilla#165]
Filter bug: when you type numbers by themselves then it sends a data type error
when you type numbers with letters in a post its fine
DOES NOT APPLY TO LIVECHAT

**Comment by oofy123** [comment]
It still works and throws datatype error.

**Comment by Mwalters75** [comment]
Ah, yes
![image](https://user-images.githubusercontent.com/67456566/156002900-9c685284-0dff-4170-ad72-06622a89b89d.png)
