### ISSUE TITLE
Typing doesn’t work on touchscreen

### ISSUE THREAD

**Issue by MrBrain295** [meower-media-co/Meower-Vanilla#168]
From my experience typing doesn’t work on touchscreen.

**Comment by Mwalters75** [comment]
Please:

- Use a Bluetooth keyboard (if you have one, if not, use a USB keyboard with a OTG cable, or a USB to Lightning cable if you have a Apple device)
- Use a computer
- Use a unofficial Meower client that uses a onscreen keyboard (official ones would be Meower HTML5)

**Comment by MrBrain295** [comment]
Ok 👍
