### ISSUE TITLE
Better dark theme

### ISSUE THREAD

**Issue by tnix100** [meower-media-co/Meower-Vanilla#177]
Take the dark themes from Lawnmeower (made by @catonmeower).

@catonmeower said they might do it themselves.

**Comment by wgyt** [comment]
@tnix100 could we also possibly add an AMOLED mode?

**Comment by tnix100** [comment]
> 

~~dark theme already is AMOLED~~
Yeah, ask @catonmeower to make one.

**Comment by ArrowAced** [comment]
I believe the dark modes in the Beta 6 screenshots were different, so I'm not sure what's happening with this

@MikeDev101

**Comment by MikeDev101** [comment]
B6P1 implements an updated Dark theme. Will leave this issue up FTTB as there is room for improvement.

**Comment by tnix100** [comment]
There's a better dark theme in svelte, Meower Vanilla's main stuff is not being updated anymore.
