### ISSUE TITLE
Graphical glitches with home and messages screen

### ISSUE THREAD

**Issue by mdwalters** [meower-media-co/Meower-Vanilla#187]
![Screenshot_2022-08-17-15-39-15](https://user-images.githubusercontent.com/67456566/185229299-f402648f-c4d5-4188-992b-c969259f8547.png)

**Comment by JoshAtticus** [comment]
Hello md, you seem to have a lot of tabs open in your web browser. Have you tried closing some?

**Comment by mdwalters** [comment]
> Hello md, you seem to have a lot of tabs open in your web browser. Have you tried closing some?

no

**Comment by JoshAtticus** [comment]
Hmm, have you considered using a different client? Meower Svelte will (soon) have a PWA manifest, so you can install it as an app.

**Comment by mdwalters** [comment]
> Hmm, have you considered using a different client? Meower Svelte will (soon) have a PWA manifest, so you can install it as an app.

i concidered meower svelte

**Comment by JoshAtticus** [comment]
> > Hmm, have you considered using a different client? Meower Svelte will (soon) have a PWA manifest, so you can install it as an app.
> 
> i concidered meower svelte

Meower Svelte can now be installed as an app on iOS and Android.

**Comment by mdwalters** [comment]
Ok

**Comment by MikeDev101** [comment]
Closing as not planned. We are retiring the Vanilla client after the CL4 port.
