### ISSUE TITLE
B6P1 Modules//GUI: Setting RGB colors to sprites sometimes doesn't work as expected

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Vanilla#189]
This is a bug that I have been working around during the development of B6P1, particularly with shades of gray. Color hex values between #000000 and #777777 are pure black, but then #888888 to #ffffff are just pure white. I believe this might just be a bug in the Scratch VM, but IDK.

**Comment by tnix100** [comment]
B6 is not being worked on anymore.
