### ISSUE TITLE
B6P1 MeowEngine//Renderer: Maximum scroll range is sometimes buggy

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Vanilla#190]
This should (hopefully) be mitigated in B6P1, however, there is always the possibility of the precalculation phase of the rendering engine incorrectly calculating the total size of all posts, which causes posts not correctly to appear at the bottom of the screen when scrolling.

**Comment by tnix100** [comment]
B6 is not being worked on anymore.
