### ISSUE TITLE
Patch: BG Music Selection Blank?

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower-Vanilla#192]
![image](https://user-images.githubusercontent.com/93960460/187267903-c24e03cf-7051-47cf-9178-b0b552b58094.png)
i did use the parody edition and changed the bg music also, but i cant select another song in vanilla

**Comment by ArrowAced** [comment]
Do you mean you changed it to one in the parody edition, and now it's broken in Vanilla? If so, spam left on the BGM select

**Comment by Bloctans** [comment]
ok

**Comment by Bloctans** [comment]
workaround found
