### ISSUE TITLE
How do i Package the project

### ISSUE THREAD

**Issue by Tycho10101** [meower-media-co/Meower-Vanilla#209]

**Comment by williamhorning** [comment]
You can use Turbowarp Packager to do so

**Comment by tnix100** [comment]
> You can use Turbowarp Packager to do so

Probably needs more details than that, like what settings to use. Which I am not sure about. Cc @MikeDev101

**Comment by Tycho10101** [comment]
> You can use Turbowarp Packager (https://packager.turbowarp.org/) to do so

Ik, But how do i get the extension to compile with the project?

**Comment by tnix100** [comment]
> > You can use Turbowarp Packager (https://packager.turbowarp.org/) to do so
> 
> Ik, But how do i get the extension to compile with the project?

Paste the code from these 2 extensions into the "Custom JS" field:
https://raw.githubusercontent.com/MikeDev101/mikedev101.github.io/master/turbo_networking.js
https://raw.githubusercontent.com/meower-media-co/Meower-Vanilla/main/utils.js

**Comment by williamhorning** [comment]
@tnix100 I'm pretty sure all of the speed-related options work just fine and 250PFS works

**Comment by MikeDev101** [comment]
Closing since Vanilla has been retired.
