### ISSUE TITLE
User online/offline notifs

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Vanilla#23]
^

**Comment by Bloctans** [comment]
umm, what about just, pinging he user every 10 seconds. once again for that error you said in the scratch forum, i quoted with:
lil idea, heres some python persudocode:
pingconnection).every(10 seconds)
if ping.fails then
connection.close
else
re run this code

**Comment by Bloctans** [comment]
also can you go fork my wikimeower into here or invite me so i can figure out how to move it into here?

**Comment by TermOfficial** [comment]
Kinda what bloctans said, except you just check the "usernames" variable block and look for the username. (all connected users are saved to a var) If the var doesn't match, send the global message

**Comment by Pixelation-Creations** [comment]
> umm, what about just, pinging he user every 10 seconds. once again for that error you said in the scratch forum, i quoted with: lil idea, heres some python persudocode: pingconnection).every(10 seconds) if ping.fails then connection.close else re run this code

what about lag with that
meower's advertized as fast and reliable

**Comment by CST1229** [comment]
> also can you go fork my wikimeower into here or invite me so i can figure out how to move it into here?

wikimeower is already here

**Comment by wgyt** [comment]
user online and offline notifs shouldn't be super hard, looking at the underlying cloudlink protocol, the ulist command is sent when someone goes online or offline, we could try to listen for changes to this

**Comment by tnix100** [comment]
Adding another suggestion to this, we could have an epoch time stored for when they last pinged the server, if the epoch time is over let's say 2 minutes then they're considered offline. The ping function will just be the built in one that helps keep the connection alive.

I also like the idea of using ulist, it's simple and already in CloudLink, will just have to implement client side.

**Comment by MikeDev101** [comment]
Easiest thing to do is check the length of the username list to show how many people are online.

**Comment by Bloctans** [comment]
isnt this added in the latest beta 5 preview?
