### ISSUE TITLE
Forgot pass needed?

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Vanilla#49]
<div type='discussions-op-text'>

<sup>Originally posted by **Glitched-Exe** November 19, 2021</sup>
I can probably whip up a forgot password feature, is it needed?</div>

**Comment by yoo832** [comment]
Probably.

**Comment by Josiah76** [comment]
This should be an option, My friend and I was about to go on meower when he forgot his password. We should make it a feature.

**Comment by MikeDev101** [comment]
Planned for Beta 5.x server rewrite and Beta 6.

**Comment by Josiah76** [comment]
> Planned for Beta 5.x server rewrite and Beta 6.

Ok, will this need backend (server) code?

**Comment by MikeDev101** [comment]
> > Planned for Beta 5.x server rewrite and Beta 6.
> 
> Ok, will this need backend (server) code?

Yes

**Comment by MikeDev101** [comment]
Closing as not planned, we are retiring the Vanilla client after the CL4 port.
