### ISSUE TITLE
Bluelist Checking Client Side

### ISSUE THREAD

**Issue by tnix100** [meower-media-co/Meower-Vanilla#80]
When looking around the source code I noticed that the client is what checks to see if the input is bluelisted, this really should be server side since people could create their own forks of the client which removes the bluelist. Unless you also check to see if something's bluelisted when it's received on the person's client, this really should be server side.

**Comment by MikeDev101** [comment]
Meower is in need of some server-side improvements, so I suppose implementing BlueList checks server-side would be better.

**Comment by MikeDev101** [comment]
why did this close? it's still not implemented yet.

**Comment by MikeDev101** [comment]
temporarily locking until we come to a consensus on keeping or removing Bluelist.

**Comment by MikeDev101** [comment]
Closed since Bluelist has been abandoned
