### ISSUE TITLE
Delete account in settings (sub-menu danger zone like github)

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Vanilla#96]
<div type='discussions-op-text'>

<sup>Originally posted by **TermOfficial** November 17, 2021</sup>
^
Small explanation:

At the bottom of settings, there will be a button to access the danger zone, with a prompt after clicking that goes like this:
"Warning; you're about to enter a dangerous zone, my friend, and you could potentially do things to your account you don't wanna do. You sure you wanna enter this mode?" 

TD;LR Warning: Danger zone could potentially destroy your account, continue?

After, you have the dangerous delete account option. (and the back button :P)</div>

**Comment by Mwalters75** [comment]
I like that! Sorta funny 😄

**Comment by wgyt** [comment]
the final button should be "commit kermit internal die"
